# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 980ec8d8ba93123a60b71b0e290f06616b2430706e1c0c08d87e5885c1f74416e2bf414b9271b42d0ff161f99c5f84d2d100ea795a0293705fc0a76e045964a2

test:
  secret_key_base: 37647f0ed35bfb323dd1f2c7089f218f1a97ea0b978efdf4e89f2d6d30e583ae040a1ffa6a89b05f1b9d980cca9176aa088c47c641975e2a717c0d782f72b591

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
